---
  DesignateBasic.create_and_delete_zone:
    -
      runner:
        type: "constant"
        times: 10
        concurrency: 10
      context:
        quotas:
          designate:
            zones: 100
            zone_recordsets: 500
            zone_records: 2000
            recordset_records: 2000
        users:
          tenants: 2
          users_per_tenant: 2
      sla:
        failure_rate:
          max: 0
